[package]
name = "lsmxzy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
crossbeam-skiplist = "0.1"
parking_lot = "0.12"
ouroboros = "0.18"

[dev-dependencies]
tempfile = "3"
